#!/bin/bash
# generate_certs.sh — PKI generation for the capstone lab.
#
# Generates:
#   ca.{key,crt}          — 4096-bit RSA root CA, 365-day self-signed
#   controller.{key,crt}  — 2048-bit RSA, signed by CA, 365-day, CN=controller
#   nginx.{key,crt}       — 2048-bit RSA, self-signed, SAN=IP:<HOST_IP>
#   whitelist.txt         — initially empty; controller appends serials at runtime
#
# NOTE (BP2): no implant cert/key is generated here.  The implant generates its
# own keypair at runtime and receives a CA-signed cert from the controller on
# first contact (enrollment-on-first-contact).
#
# Also writes:
#   ../c2-server/C2-Server-and-Implant/include/implant_certs.h
#     — C byte array for the CA cert only (BP2: key never embedded in binary)
#
# Usage: ./generate_certs.sh <HOST_IP>

set -eo pipefail

HOST_IP="${1:?Usage: $0 <HOST_IP>}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "[pki] Generating PKI for HOST_IP=${HOST_IP}"

# ── CA ────────────────────────────────────────────────────────────────
# Only generate a new CA if one doesn't already exist.  Preserving the CA
# across ./launch.sh runs means already-installed implants (which have the
# old CA cert baked in) can still re-enroll and reconnect after the
# c2-server container is rebuilt — they don't need to be redeployed.
# Delete certs/ca.key and certs/ca.crt manually to force a full rotation.
if [ -f ca.key ] && [ -f ca.crt ]; then
    echo "[pki] CA already exists — reusing (delete certs/ca.key + ca.crt to rotate)"
else
    openssl genrsa -out ca.key 4096 2>/dev/null
    openssl req -new -x509 -days 365 -key ca.key -out ca.crt \
        -subj "/CN=Lab CA/O=CS564/C=US" 2>/dev/null
    echo "[pki] CA generated (new)"
fi

# ── Controller cert (signed by CA, 365-day) ───────────────────────────
openssl genrsa -out controller.key 2048 2>/dev/null
openssl req -new -key controller.key -out controller.csr \
    -subj "/CN=controller/O=CS564/C=US" 2>/dev/null
openssl x509 -req -days 365 -in controller.csr \
    -CA ca.crt -CAkey ca.key -CAcreateserial \
    -out controller.crt 2>/dev/null
rm -f controller.csr
echo "[pki] Controller cert generated (365-day)"

# ── BP4: whitelist — preserve existing serials across restarts ─────────
# Only reset the whitelist when the CA is being rotated (i.e. whitelist.txt
# doesn't exist yet).  On subsequent runs the controller appends new serials
# so existing enrolled implants remain whitelisted.
if [ ! -f whitelist.txt ]; then
    echo "# BP4 serial whitelist — one hex serial per line"  >  whitelist.txt
    echo "# Controller appends implant serials during enrollment (BP2)"     >> whitelist.txt
    echo "[pki] Whitelist initialised (empty — serials added by controller at runtime)"
else
    echo "[pki] Whitelist preserved ($(grep -c '^[0-9a-fA-F]' whitelist.txt 2>/dev/null || echo 0) enrolled serials)"
fi

# ── nginx cert (self-signed with SAN=IP:<HOST_IP>) ────────────────────
cat > /tmp/nginx_ext.cnf <<EOF
[req]
distinguished_name = req_dn
x509_extensions    = v3_req
prompt             = no
[req_dn]
CN = ${HOST_IP}
[v3_req]
subjectAltName = IP:${HOST_IP}
EOF

openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout nginx.key -out nginx.crt \
    -days 365 -config /tmp/nginx_ext.cnf 2>/dev/null
rm -f /tmp/nginx_ext.cnf
echo "[pki] nginx cert generated with SAN=IP:${HOST_IP}"

# ── Generate implant_certs.h ──────────────────────────────────────────
HEADER_OUT="${SCRIPT_DIR}/../c2-server/C2-Server-and-Implant/include/implant_certs.h"

python3 - <<PYEOF
import sys

def to_c_array(name, path):
    data = open(path, 'rb').read()
    items = ', '.join(f'0x{b:02x}' for b in data)
    return (f'static const unsigned char {name}[] = {{{items}}};\n'
            f'static const int {name}_len = {len(data)};\n')

out = [
    '#pragma once',
    '/* Auto-generated by generate_certs.sh — do not edit or commit */',
    '/* BP1/BP2: CA cert only — lets the implant verify the controller.  */',
    '/* The implant generates its own keypair at runtime (BP2).          */',
    '',
    to_c_array('implant_ca_cert_pem', '${SCRIPT_DIR}/ca.crt'),
]
open('${HEADER_OUT}', 'w').write('\n'.join(out) + '\n')
print('[pki] implant_certs.h written to ${HEADER_OUT}')
PYEOF

echo "[pki] PKI generation complete."
echo ""
echo "  CA cert:         certs/ca.crt (+ ca.key for controller enrollment)"
echo "  Controller:      certs/controller.{crt,key}"
echo "  nginx:           certs/nginx.{crt,key}"
echo "  Whitelist:       certs/whitelist.txt  (empty — serials added at runtime)"
echo "  C header:        c2-server/C2-Server-and-Implant/include/implant_certs.h"
