#!/bin/bash

# ─────────────────────────────────────────────
#  Capstone Docker Lab — Launch Script
# ─────────────────────────────────────────────

set -eo pipefail
# Note: use || true on commands that are allowed to fail (e.g. docker compose down with nothing running)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}       Capstone Docker Lab — Launch Script      ${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""

# ── 1. Check dependencies ─────────────────────
echo -e "${YELLOW}[*] Checking dependencies...${NC}"

if ! command -v docker &>/dev/null; then
    echo -e "${RED}[!] Docker is not installed. Install it and try again.${NC}"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo -e "${RED}[!] Docker Compose plugin not found. Install it and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}[+] Docker and Docker Compose found.${NC}"

# ── 2. Detect available host IPs ─────────────
echo ""
echo -e "${YELLOW}[*] Detecting network interfaces...${NC}"
echo ""
echo -e "    ${YELLOW}NOTE: Your Windows VM must use a Host-Only adapter in VirtualBox.${NC}"
echo -e "    Use the ${GREEN}vboxnet0${NC} IP below as your C2_HOST_IP."
echo ""

mapfile -t IFACES < <(ip -o -4 addr show | awk '{print $2, $4}' | grep -v '^lo ' | grep -v '127\.')

HOSTONLY_IP=""
if [ ${#IFACES[@]} -eq 0 ]; then
    echo -e "${RED}[!] No non-loopback IPv4 interfaces found.${NC}"
else
    echo "    Available IPs:"
    for iface in "${IFACES[@]}"; do
        IFACE_NAME=$(echo "$iface" | awk '{print $1}')
        IFACE_IP=$(echo "$iface" | awk '{print $2}' | cut -d'/' -f1)
        if [[ "$IFACE_NAME" == vboxnet* || "$IFACE_NAME" == vmnet* ]]; then
            echo -e "      ${GREEN}$IFACE_NAME${NC} → $IFACE_IP  ${CYAN}← recommended (host-only)${NC}"
            HOSTONLY_IP="$IFACE_IP"
        else
            echo -e "      ${GREEN}$IFACE_NAME${NC} → $IFACE_IP"
        fi
    done
fi

# ── 3. Prompt for host IP ─────────────────────
echo ""
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}[*] No .env file found — creating one now.${NC}"
fi

CURRENT_IP=$(grep -oP '(?<=C2_HOST_IP=)\S+' "$ENV_FILE" 2>/dev/null || echo "")

# Pre-fill with host-only IP if detected and no existing .env
DEFAULT_IP="${CURRENT_IP:-$HOSTONLY_IP}"

if [ -n "$CURRENT_IP" ]; then
    echo -e "${YELLOW}[*] Current C2_HOST_IP in .env: ${GREEN}$CURRENT_IP${NC}"
    read -rp "    Enter new host IP (or press Enter to keep '$CURRENT_IP'): " INPUT_IP
    HOST_IP="${INPUT_IP:-$CURRENT_IP}"
elif [ -n "$HOSTONLY_IP" ]; then
    echo -e "${YELLOW}[*] Detected host-only adapter IP: ${GREEN}$HOSTONLY_IP${NC}"
    read -rp "    Press Enter to use '$HOSTONLY_IP' or enter a different IP: " INPUT_IP
    HOST_IP="${INPUT_IP:-$HOSTONLY_IP}"
else
    read -rp "    Enter your Linux host IP (e.g. 192.168.56.1): " HOST_IP
fi

# Validate IP format
if ! echo "$HOST_IP" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
    echo -e "${RED}[!] Invalid IP address: '$HOST_IP'. Exiting.${NC}"
    exit 1
fi

echo -e "${GREEN}[+] Using C2_HOST_IP=${HOST_IP}${NC}"

# Write to .env
cat > "$ENV_FILE" <<EOF
# Your Linux host IP address — baked into implant.exe at build time.
# Regenerated by launch.sh on $(date)
C2_HOST_IP=${HOST_IP}
EOF

echo -e "${GREEN}[+] .env written.${NC}"

# ── 4. Shellcode generation ───────────────────
echo ""
echo -e "${GREEN}[+] Shellcode will be generated inside the Docker build:${NC}"
echo -e "    loader.c → loader.exe (mingw-w64) → loader.bin (Donut) → patched into exploit.js"

# ── 5. Stop any existing lab containers ───────
echo ""
echo -e "${YELLOW}[*] Stopping any existing lab containers...${NC}"
docker compose -f "$COMPOSE_FILE" down 2>/dev/null || true
echo -e "${GREEN}[+] Ready to rebuild.${NC}"

# ── 6. Check for port conflicts ───────────────
echo ""
echo -e "${YELLOW}[*] Checking for port conflicts (4444, 8000, 8888)...${NC}"

CONFLICT=0
for PORT in 4444 8000 8888; do
    if ss -tlnp 2>/dev/null | grep -q ":${PORT} "; then
        echo -e "${RED}[!] Port $PORT is already in use.${NC}"
        CONFLICT=1
    fi
done

if [ $CONFLICT -eq 1 ]; then
    read -rp "    Port conflicts detected. Continue anyway? (y/N): " CONFIRM
    CONFIRM="${CONFIRM:-N}"
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${RED}[!] Exiting. Free up the conflicting ports and try again.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}[+] No port conflicts.${NC}"
fi

# ── 7. Build and launch ───────────────────────
echo ""
echo -e "${YELLOW}[*] Building and launching containers (this may take a few minutes)...${NC}"
echo ""

docker compose -f "$COMPOSE_FILE" up --build -d

# ── 8. Verify containers are running ─────────
echo ""
echo -e "${YELLOW}[*] Verifying containers started...${NC}"
sleep 3

ALL_UP=1
for NAME in c2-server exfil-server; do
    STATUS=$(docker inspect --format='{{.State.Status}}' "$NAME" 2>/dev/null || echo "missing")
    if [ "$STATUS" = "running" ]; then
        echo -e "    ${GREEN}[+] $NAME is running${NC}"
    else
        echo -e "    ${RED}[!] $NAME is NOT running (status: $STATUS)${NC}"
        ALL_UP=0
    fi
done

# ── 9. Summary ────────────────────────────────
echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}                    Summary                     ${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""
echo -e "  C2 listener      → ${GREEN}localhost:4444${NC}  (TCP)"
echo -e "  Exploit webpage  → ${GREEN}http://localhost:8888${NC}"
echo -e "  File server      → ${GREEN}http://localhost:8000${NC}"
echo ""
echo -e "  From Windows VM:"
echo -e "  Exploit webpage  → ${GREEN}http://${HOST_IP}:8888${NC}"
echo -e "  Download implant → ${GREEN}http://${HOST_IP}:8000/implant.exe${NC}"
echo -e "  C2 connects to   → ${GREEN}${HOST_IP}:4444${NC}  (baked into implant.exe)"
echo ""
echo -e "  Attach to C2 controller:"
echo -e "    ${CYAN}sudo docker attach c2-server${NC}"
echo -e "  Detach without stopping: ${CYAN}Ctrl+P then Ctrl+Q${NC}"
echo ""

if [ $ALL_UP -eq 1 ]; then
    echo -e "${GREEN}[+] Lab is up and ready.${NC}"
else
    echo -e "${RED}[!] One or more containers failed to start. Check logs:${NC}"
    echo -e "    ${CYAN}docker compose logs -f${NC}"
fi

echo ""
